<li id="prevpatrons_dropdown" class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Previous <span class="caret"></span>
    </a>

    <ul id="prevpatrons" class="dropdown-menu">
        <li id="clear_prevpatrons_wrapper" >
            <a id="clear_prevpatrons" href="javascript:void(0)">
                Clear list <i class="fa fa-trash"></i>
            </a>
        </li>
        <li id="prevpatrons_divider" class="divider"></li>
        <li id="prevpatrons_message_wrapper" class="dropdown-header">
            <p id="prevpatrons_message">No patrons saved to list</p>
        </li>

    </ul>
</li>
